databases:
  - name: todo_db
    plan: free
    databaseName: todo_db
    user: postgres

services:
  - type: web
    plan: free
    name: todo_list_proj
    runtime: python
    buildCommand: "./build.sh"  # Ensure this script is correctly created for your project
    startCommand: "python -m gunicorn todo_list_proj.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true  # Generates a secure random value for Django's SECRET_KEY
      - key: WEB_CONCURRENCY
        value: 4  # Adjust this based on the server's concurrency limit or your preference
